### ISSUE TITLE
Editor create duplicated ways as a second changeset

### ISSUE THREAD

**Issue by tordans** [zlant/parking-lanes#110]
We are mapping a lot with our berlin-edition of this editor ([Link](https://tordans.github.io/parking-lanes/#18/52.47846/13.43201)).

We are seeing an issue, where we have duplicated ways in two different changesets after editing.

## What it looks like…

The duplicated ways show up as black line in a road segment that is mapped with parking lane information (colored line)

![Bildschirmfoto 2022-05-04 um 15 36 54](https://user-images.githubusercontent.com/111561/166870388-dd5f25c0-6e17-440e-bde6-8201d8aabaeb.png)

### Example 1

| keep | delete |
|---|---|
| has the new tagging from the parking lane editor | has no new tagging |
| https://www.openstreetmap.org/changeset/120503088 | https://www.openstreetmap.org/changeset/120503070 |
| 2022-05-03 16:42 | 2022-05-03 16:42 |
| https://pewu.github.io/osm-history/#/way/1056892126 | https://pewu.github.io/osm-history/#/way/1056892103 |
| | Deleted in https://osmcha.org/changesets/120547422/ |

### Example 2

* keep https://pewu.github.io/osm-history/#/way/1054730129
* delete https://pewu.github.io/osm-history/#/way/1054729518

This one was special, because a StreetComplete user edited both ways. I assume one via the in app AR Feature and one manually afterwards.

## Cleanup process

We did a cleanup for Berlin and will look out for new ways to clean. Here is how I did that:

1. Use this view to find duplicated ways http://osmose.openstreetmap.fr/de/map/#zoom=13&lat=52.4931&lon=13.42068&item=1230&level=1%2C2%2C3 (it also shows duplicated nodes, those can be ignored for this cleanup)
2. Find the way id without the new tagging
3. Use http://level0.osmz.ru/index.php > add the way `w123` > change the name from "w123" to "-w123" in the editor, add a changeset comment "parking lanes; cleanup duplicated ways" and save.

A list of all removed duplicated ways is at https://osmcha.org/changesets/120548131?filters=%7B%22users%22%3A%5B%7B%22label%22%3A%22tordans%22%2C%22value%22%3A%22tordans%22%7D%5D%2C%22date__gte%22%3A%5B%7B%22label%22%3A%22%22%2C%22value%22%3A%22%22%7D%5D%2C%22comment%22%3A%5B%7B%22label%22%3A%22parking%20lanes%3B%20remove%22%2C%22value%22%3A%22parking%20lanes%3B%20remove%22%7D%5D%7D

**Comment by zlant** [comment]
Fixed
