### ISSUE TITLE
Proposal for a rework of the `parking:lane` schema

### ISSUE THREAD

**Issue by tordans** [zlant/parking-lanes#119]
Hey! For anyone who did not see it, yet: There is a proposal in the works with the goal of improving and reworking the `parking:lane` schema.

* Proposal https://wiki.openstreetmap.org/wiki/Proposed_features/street_parking_revision
* Discussion on the Wiki discussion page

It would be awesome to get your input on this. A explicit position of @zlant on this proposal would help a lot to either stop things before too much time is invested … or push things forward to a better solution.

Apart from editor support the most important part that help is needed with is IMO the question of data migration. Any help with this is very welcome. Could we maybe join forces to build a migration tool that will list all existing data in a bbox in a table, show the transposed new tags and allows to commit those changes to OSM? Would you be up for helping build such a tool @zlant @jakecoppinger?

**Comment by tordans** [comment]
@zlant [The proposal](https://wiki.openstreetmap.org/wiki/Proposed_features/street_parking_revision) is now officially in it's RFC state. It would be great if you could take the time to check it (again) and comment on any issues you see for this editor. A statement on "support and planned adoption" from you for this editor, which is one of the major tools to map parking data, would help the proposal a lot for it's voting phase.

Such an endorsement could IMO happen here as a comment or on the discussion page.

**On the topic of data migration:** 

We are experimenting with a tool that would help migrating the tags. More at https://github.com/osmberlin/osm-tag-updater. IMO this looks promising…

**Comment by zlant** [comment]
Hi, @tordans. I don't think I will have time to add support for the new schema in the near future.

**Comment by Marc-marc-marc** [comment]
in the meantime, the proposal is approved.
if someoneelse is doing a PR, would you have the time to merge and deploy it on your site ?
I ask this question before reading the code because of the number of pending PRs (including bugfixes in dependencies) and that unfortunately time is not infinite :)

**Comment by zlant** [comment]
Hi, @Marc-marc-marc.
Yes, I will find time for PR.
Should to save support old tagging schemes for edit. If it hard then must support only in view mode and on edit mode show link to https://github.com/osmberlin/osm-tag-updater

**Comment by tordans** [comment]
@zlant thanks a lot for this update, it really helps!

We will have new things to share on our parking lane project as well, soon. Will write an update then.

**Comment by davidpnewton** [comment]
This update is very welcome indeed.
