### ISSUE TITLE
Time-limited paid parking showing as time-limited

### ISSUE THREAD

**Issue by riiga** [zlant/parking-lanes#135]
Should probably show as paid.

[Map link](https://zlant.github.io/parking-lanes/#18/58.40688/15.64244) ([OSM way](https://www.openstreetmap.org/way/4498604))

Relevant tags:
```
parking:right:fee = yes
parking:right:maxstay:conditional = 2 hours @ (06:00-22:00)
```

**Comment by zlant** [comment]
Fixed
