### ISSUE TITLE
OSM auth doesn't work

### ISSUE THREAD

**Issue by Discostu36** [zlant/parking-lanes#136]
I can't use the integrated editor. If I try to, the OpenStreetMap authentication windows opens. I grant permission. The window goes blank but stays open. Nothing happens, editing not possible.

**Comment by Discostu36** [comment]
Console error:

`Uncaught TypeError: opener is null`

**Comment by tordans** [comment]
Will have a look...

**Comment by tordans** [comment]
@Discostu36 can you share the steps to reproduce. I tried two Szenarios but those worked fine.

**Comment by tordans** [comment]
This is a case that does work (even though I did not expect it to (the logout does not log out the app) :))

1. I logged in via the app
    I now have `oauth_*` token in my Local Storage
2. I logged out of osm.org
3. I was able to make changes and save them (without logging in again)

**Comment by Discostu36** [comment]
I can' reproduce the error myself. I am on a different machine than when it occurred. But I guess it will go away if I just clear my osm/zlant cookies on that one and try again.
