### ISSUE TITLE
Update "Tagging" link

### ISSUE THREAD

**Issue by tordans** [zlant/parking-lanes#138]
Currently the link on the bottom right links to https://wiki.openstreetmap.org/wiki/Key:parking:lane.

A better page ist now https://wiki.openstreetmap.org/wiki/Street_parking.

<img width="332" alt="image" src="https://user-images.githubusercontent.com/111561/222726418-3ac55e6b-d039-4f65-937f-1187374ed8c9.png">

**Comment by zlant** [comment]
Fixed https://github.com/zlant/parking-lanes/commit/e9429193b738eaeb2dee144b6042d6e5deb067ae
