### ISSUE TITLE
add taginfo.json

### ISSUE THREAD

**Issue by osmtools** [zlant/parking-lanes#18]
please add the [taginfo.json](https://wiki.openstreetmap.org/wiki/Taginfo/Projects) to your project.
then everybody can see your editor in the [taginfo projects](https://taginfo.openstreetmap.org/projects) and if somebody looks at the [parking:lane-keys](https://taginfo.openstreetmap.org/keys/parking:lane#projects) you can see that your editor supports these keys.

need a short example, then have a look at https://github.com/osmtools/direction/blob/master/taginfo.json

**Comment by zlant** [comment]
@osmtools yes
