### ISSUE TITLE
Some ways can't be split

### ISSUE THREAD

**Issue by Mannivu** [zlant/parking-lanes#38]
I've seen that some ways can't be split, but I can't understand why. For example, [way 117612033](https://openstreetmap.org/way/117612033) can't be split
![image](https://user-images.githubusercontent.com/42747216/125659818-d5b1da70-0e02-4690-b8f5-dc0439f146c9.png)

but [way 139886052](https://openstreetmap.org/way/139886052) can.
![image](https://user-images.githubusercontent.com/42747216/125659972-690c2608-dfb0-4b2c-a1da-6dabbe12d815.png)

**Comment by zlant** [comment]
If way is member of relation then can't split. I haven't learned how to do it right yet.

**Comment by Mannivu** [comment]
Oh, ok. That makes sense, I hadn't thought about relations.

**Comment by tordans** [comment]
Ping https://github.com/ideditor/id-sdk/issues/165, which might help at some point to improve this feature.
