### ISSUE TITLE
Does the date picker still work? With both data sources?

### ISSUE THREAD

**Issue by tordans** [zlant/parking-lanes#53]
I was wondering how the date feature works after https://github.com/zlant/parking-lanes/pull/52.

But while testing it on https://zlant.github.io/parking-lanes/#17/52.47906/13.42876, I think I was not able to get it to do anything at all.

* Does it work at all ATM? (If so, what is the click-by-click way to use it?)
* Does it work with both overpass and OSM data?

My assumption was, that it would only work with overpass and that the datepicker should maybe be hidden if the datasource is OSM directly.

**Comment by zlant** [comment]
This pull request must not affect the work of the date picker. OSM and Overpass data do not differ.

**Comment by zlant** [comment]
> Do you have an example URL, where that can be seen in action? It looks like in my area no tagging that would effect this change is used.

https://zlant.github.io/parking-lanes/#18/52.47893/13.43178 (this way https://www.openstreetmap.org/way/32118083)
