### ISSUE TITLE
Misleading capacity tag

### ISSUE THREAD

**Issue by thuryn** [zlant/parking-lanes#60]
I've found your app uses tag parking:condition:left:capacity, OSM WIKI (https://wiki.openstreetmap.org/wiki/Key:parking:lane#parking:lane:side:type-street_side) recommend parking:lane:left:capacity which seams to be more meaningful to me. Are you going to unify your app with this suggestion?

**Comment by zlant** [comment]
Thank you for noticing the error, I will try to fix it in the near future
