### ISSUE TITLE
Change colors for people with Red Green weakness

### ISSUE THREAD

**Issue by tordans** [zlant/parking-lanes#78]
I received the feedback that the colors of the app are an issue for people with red green weakness.

Will try some other colors and collect more feedback. 

Wanted to raise this here first to let you know and maybe someone has colors preferences?

I [tried this simulator](https://www.color-blindness.com/coblis-color-blindness-simulator/) to get a feel for the issue. No idea how good that is though (or which option to optimize for)… 

<img width="780" alt="image" src="https://user-images.githubusercontent.com/111561/152679140-99f1a2b1-5688-421f-ba9d-c10b0ab6861e.png">

<img width="581" alt="Bildschirmfoto 2022-02-06 um 12 39 32" src="https://user-images.githubusercontent.com/111561/152679146-2efebc1a-8eed-463d-8e2c-128774f6be36.png">

**Comment by tordans** [comment]
https://colorbrewer2.org/#type=diverging&scheme=PuOr&n=4 was recommended to me.
It looks like a good candidate is…

- `#e66101` / `#fdb863`
   vs.
- `#5e3c99` / `#b2abd2`

**Comment by zlant** [comment]
![image](https://user-images.githubusercontent.com/8606466/152698361-9721b9be-2c77-4598-a28b-85e2c63c0d31.png)

**Comment by tordans** [comment]
@zlant from the feedback I received this is a good solution!

**Comment by tordans** [comment]
Thanks looks good at https://zlant.github.io/parking-lanes/#18/52.50759/13.46244
