### ISSUE TITLE
Allow different viewer visualization based on direction, not condition

### ISSUE THREAD

**Issue by tordans** [zlant/parking-lanes#82]
Right now, the visualization view tells the story "am I allowed to park here (at this time) and what are the conditions?".

However, for a first mapping campaign the data about `parking:condition` is not feasible, since that is data that requires ground truth / survey, not just areal images.
Instead, it would be great to have the story "am I allowed to park here (at this time) (and in what direction)?" visualized.

Quite [a few areas](https://zlant.github.io/parking-lanes/#18/52.50713/13.46270) in Berlin have tags like 
> parking:lane:left=parallel
parking:lane:left:parallel=on_street
parking:lane:right=perpendicular
parking:lane:right:perpendicular=on_street

But nothing of that gets visualized in the viewer.x

I tried changing this logic myself in my Fork in December, but the change was too broad for me to get done. I fell back to just showing two lines per side, one for the existing visualization and another of the "direction", but did not finish this either.

**Comment by zlant** [comment]
Now free condition when only lane tag

**Comment by tordans** [comment]
Thanks, that change is a good idea which solves most of my issue.
