### ISSUE TITLE
No specified npm version - add a `.nvmrc`

### ISSUE THREAD

**Issue by jakecoppinger** [zlant/parking-lanes#94]
Currently when I run `npm i` the `package-lock.json` has a lot of changes and upgrades the lockfile version.

Adding a `.nvmrc` and using `nvm` is an easy way to make sure we all use the same `nvm` version.

See https://github.com/nvm-sh/nvm.

I'm happy to make a PR for this (including README docs) if you let me know your preferred Node version!

**Comment by zlant** [comment]
Now installed node 14.17.0
